const ESTADOS_DEVOLUCION = Object.freeze({
  DEVUELTO: "DEVUELTO",
  DANADO: "DANADO",
  PERDIDO: "PERDIDO",
  ROBADO: "ROBADO",
});

const ESTADOS_EQUIPO_OBJETIVO = Object.freeze({
  [ESTADOS_DEVOLUCION.DEVUELTO]: "Disponible",
  [ESTADOS_DEVOLUCION.DANADO]: "En Mantenimiento",
  [ESTADOS_DEVOLUCION.PERDIDO]: "De baja",
  [ESTADOS_DEVOLUCION.ROBADO]: "De baja",
});

const ESTADOS_EQUIPO_IDS_ESPERADOS = Object.freeze({
  Disponible: 1,
  "En Mantenimiento": 2,
  "De baja": 3,
});

const CONSISTENCIA_DEVUELTO = Object.freeze({
  [ESTADOS_DEVOLUCION.DEVUELTO]: 1,
  [ESTADOS_DEVOLUCION.DANADO]: 1,
  [ESTADOS_DEVOLUCION.PERDIDO]: 0,
  [ESTADOS_DEVOLUCION.ROBADO]: 0,
});

module.exports = {
  ESTADOS_DEVOLUCION,
  ESTADOS_EQUIPO_OBJETIVO,
  ESTADOS_EQUIPO_IDS_ESPERADOS,
  CONSISTENCIA_DEVUELTO,
};
